[package]
name = "text-analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my-cryptopals-lib = { path = "../../my-cryptopals-lib" }
